services:
  server:
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gobanking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine
    container_name: banking_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gobanking
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gobanking"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: banking_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
